### ISSUE TITLE
`ns not found` internal server error

### ISSUE THREAD

**Issue by chavda-bhavik** [implerhq/impler.io#541]
**Describe the bug**
While clicking on the `Upload Again` button from the second mapping stage, the API doesn't work and throws the error `ns not found` internally.

**To Reproduce**
1. Create a new import and add a few columns.
2. Click on the `Import` button.
3. Upload Excel or CSV file.
4. Click on `See Mapping`
5. On the second stage click on the `Upload Again` button, it will not work.

**Expected behavior**
The `Upload Again` button should work without any respect of where the user is.

**Screenshots**
Error backend API is throwing,
![image](https://github.com/implerhq/impler.io/assets/50201755/e2b2ecd8-5328-4266-9357-d2311f4746ea)

**Desktop (please complete the following information):**
 - Version `0.18.0`

**Additional context**
As per the research, the error is occurring due to MongoDB collection not being found. So in terminate API, we can add a check if the Mongodb collection exists then and then only try to delete it.

**Comment by HarjobandeepSingh** [comment]
@chavda-bhavik  issue might be due to the MongoDB collection not being created yet or the name of the collection being incorrect.

**Comment by austinStan** [comment]
@HarjobandeepSingh is this available..im a beginner need an issue to start with.

**Comment by chavda-bhavik** [comment]
Hey @HarjobandeepSingh Thanks that was the issue. We fixed it recently.

**Comment by chavda-bhavik** [comment]
hey @austinStan If you're open to contribution, please join [Discord](https://discord.impler.io) to chat with the team or we have recently added new issues too.

**Comment by austinStan** [comment]
@chavda-bhavik thanks..lemme do that right away
