### ISSUE TITLE
Unable to setup locally

### ISSUE THREAD

**Issue by chavda-bhavik** [implerhq/impler.io#612]
### Discussed in https://github.com/implerhq/impler.io/discussions/547

<div type='discussions-op-text'>

<sup>Originally posted by **HarjobandeepSingh** April 19, 2024</sup>
i really want to contribute and also followed contribute.md file step by step but still on first command getting so many errors and also i think some steps are missing and also about .env file ?</div>

**Comment by kunnu223** [comment]
https://github.com/implerhq/impler.io/pull/749
