### ISSUE TITLE
Flow improvement to Bubble.io destination

### ISSUE THREAD

**Issue by chavda-bhavik** [implerhq/impler.io#616]
**Describe the bug**
Bubble.io destination follows this step,
1. Add `Bubble App Name`
2. Add a `Custom Domain Name` only if the site runs on production.
3. Choose `Environment`
4. Provide `API Private Key`
5. Provide `Datatype Name`

![Screenshot from 2024-06-25 13-08-59](https://github.com/implerhq/impler.io/assets/50201755/5a747e83-52fe-40dd-abda-3181f52698a2)

It confuses users and they provide a `Custom Domain Name` which leads to data sending to the production environment. It fails for reasons like the app not being available, the app not being live, etc.

**Additional context**
We can bring `Custom Domain Name` down to `Environment` and only show it when the environment is in production.

**Comment by ParthJohri** [comment]
Greetings @chavda-bhavik , I would like to work on this issue, can you please assign it to me?

Please let me know if I understood correctly, we have to move down the custom domain name input field down a row which is below the environment input field, to prevent the failures. 
Also, do you also mean to hide the custom domain name field if the environment is not in production?

Thank you!

**Comment by chavda-bhavik** [comment]
Hey @ParthJohri Sorry to inform you that, due to urgency we had to do it and make it live. You can check out this https://github.com/implerhq/impler.io/issues/721 which might interest you. You can join our [discord](https://discord.impler.io) too where we can discuss about more available issues.
