### ISSUE TITLE
Sample file doesn't include default data when downloaded

### ISSUE THREAD

**Issue by r-yeganeh** [implerhq/impler.io#797]
**Describe the bug**
Sample file in widget modal doesn't include default data when downloaded even though passed in showWidget params.

**To Reproduce**
This is the code for widget button:
```
const sampleStudents = [
  {
    first: "foo",
    last: "bar",
    age: 25,
  },
  {
    first: "foo",
    last: "bar",
    age: 21,
  },
];
...
<button
      disabled={!isImplerInitiated}
      onClick={() => {
        showWidget({ data: sampleStudents });
      }}
    >
      Import
</button>
I checked template to make sure property names are correct.
```

**Expected behavior**
Downloaded sample file should include sample students data.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: chrome
 - Version: 123

**Comment by chavda-bhavik** [comment]
@r-yeganeh Thanks for sharing your issue, just resolved it. It will be available in 15-20 minutes.

**Comment by chavda-bhavik** [comment]
@r-yeganeh I will update you as it goes live!

**Comment by chavda-bhavik** [comment]
@r-yeganeh It's released!

**Comment by r-yeganeh** [comment]
> @r-yeganeh It's released!

Thank you Bhavik! It works fine now.
