### ISSUE TITLE
Fix code scanning alert - Database query built from user-controlled sources

### ISSUE THREAD

**Issue by thisismayuresh** [implerhq/impler.io#881]
**Description**

Implementing additional safety measures for database queries in libs/dal/src/repositories/base-repository.ts. This enhancement focuses on improving input handling in the findOneAndUpdate method.

**Current Implementation**

```
protected async findOneAndUpdate(
    query: FilterQuery<T>,
    updateBody: UpdateQuery<T>,
    options: QueryOptions<T> = { new: true }
): Promise<T> {
    return this.MongooseModel.findOneAndUpdate(query, updateBody, options);
}

```

**Comment by saksham-malhotra-27** [comment]
Hey ! is this still open or assigned already ?

**Comment by sinanptm** [comment]
Thank you for your request. The issue has already been assigned to me, and I am currently handling it. In fact, I have already submitted a pull request, and it is now being tested.
